package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HelpContent generated by hbm2java
 */
public class HelpContent  implements java.io.Serializable {


     private String id;
     private String name;
     private String url;
     private String title;
     private String shortDescrption;
     private String descrption;
     private String icon;
     private Integer dataSort;
     private Date createTime;
     private String categoryId;

    public HelpContent() {
    }

	
    public HelpContent(String id) {
        this.id = id;
    }
    public HelpContent(String id, String name, String url, String title, String shortDescrption, String descrption, String icon, Integer dataSort, Date createTime, String categoryId) {
       this.id = id;
       this.name = name;
       this.url = url;
       this.title = title;
       this.shortDescrption = shortDescrption;
       this.descrption = descrption;
       this.icon = icon;
       this.dataSort = dataSort;
       this.createTime = createTime;
       this.categoryId = categoryId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getShortDescrption() {
        return this.shortDescrption;
    }
    
    public void setShortDescrption(String shortDescrption) {
        this.shortDescrption = shortDescrption;
    }
    public String getDescrption() {
        return this.descrption;
    }
    
    public void setDescrption(String descrption) {
        this.descrption = descrption;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Integer getDataSort() {
        return this.dataSort;
    }
    
    public void setDataSort(Integer dataSort) {
        this.dataSort = dataSort;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }




}


