package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * HrEmployee generated by hbm2java
 */
public class HrEmployee  implements java.io.Serializable {


     private String id;
     private String realName;
     private String userId;
     private Integer sex;
     private String tel;
     private String moblie;
     private String idNo;
     private String departmentPositionId;

    public HrEmployee() {
    }

	
    public HrEmployee(String id) {
        this.id = id;
    }
    public HrEmployee(String id, String realName, String userId, Integer sex, String tel, String moblie, String idNo, String departmentPositionId) {
       this.id = id;
       this.realName = realName;
       this.userId = userId;
       this.sex = sex;
       this.tel = tel;
       this.moblie = moblie;
       this.idNo = idNo;
       this.departmentPositionId = departmentPositionId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMoblie() {
        return this.moblie;
    }
    
    public void setMoblie(String moblie) {
        this.moblie = moblie;
    }
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }
    public String getDepartmentPositionId() {
        return this.departmentPositionId;
    }
    
    public void setDepartmentPositionId(String departmentPositionId) {
        this.departmentPositionId = departmentPositionId;
    }




}


