package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HrPosition generated by hbm2java
 */
public class HrPosition  implements java.io.Serializable {


     private String id;
     private String positionName;
     private String description;
     private Integer dataStatus;
     private Integer levelId;
     private Date createTime;
     private String createUserId;
     private Date lastUpdateTime;
     private String lastUpdateUserId;

    public HrPosition() {
    }

	
    public HrPosition(String id) {
        this.id = id;
    }
    public HrPosition(String id, String positionName, String description, Integer dataStatus, Integer levelId, Date createTime, String createUserId, Date lastUpdateTime, String lastUpdateUserId) {
       this.id = id;
       this.positionName = positionName;
       this.description = description;
       this.dataStatus = dataStatus;
       this.levelId = levelId;
       this.createTime = createTime;
       this.createUserId = createUserId;
       this.lastUpdateTime = lastUpdateTime;
       this.lastUpdateUserId = lastUpdateUserId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPositionName() {
        return this.positionName;
    }
    
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getDataStatus() {
        return this.dataStatus;
    }
    
    public void setDataStatus(Integer dataStatus) {
        this.dataStatus = dataStatus;
    }
    public Integer getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public String getLastUpdateUserId() {
        return this.lastUpdateUserId;
    }
    
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }




}


