package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysAdministrativeRegion generated by hbm2java
 */
public class SysAdministrativeRegion  implements java.io.Serializable {


     private String id;
     private String regionCode;
     private String regionName;
     private String parentCode;
     private String longitude;
     private String latitude;
     private String compatibleCode;

    public SysAdministrativeRegion() {
    }

	
    public SysAdministrativeRegion(String id, String regionCode) {
        this.id = id;
        this.regionCode = regionCode;
    }
    public SysAdministrativeRegion(String id, String regionCode, String regionName, String parentCode, String longitude, String latitude, String compatibleCode) {
       this.id = id;
       this.regionCode = regionCode;
       this.regionName = regionName;
       this.parentCode = parentCode;
       this.longitude = longitude;
       this.latitude = latitude;
       this.compatibleCode = compatibleCode;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRegionCode() {
        return this.regionCode;
    }
    
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }
    public String getParentCode() {
        return this.parentCode;
    }
    
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getCompatibleCode() {
        return this.compatibleCode;
    }
    
    public void setCompatibleCode(String compatibleCode) {
        this.compatibleCode = compatibleCode;
    }




}


