package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysConfig generated by hbm2java
 */
public class SysConfig  implements java.io.Serializable {


     private String id;
     private String moduleGroupId;
     private String name;
     private int style;
     private byte canAddOrDelete;
     private String customCategoryId;
     private String jsonData;
     private String description;
     private String groupName;

    public SysConfig() {
    }

	
    public SysConfig(String id, int style, byte canAddOrDelete) {
        this.id = id;
        this.style = style;
        this.canAddOrDelete = canAddOrDelete;
    }
    public SysConfig(String id, String moduleGroupId, String name, int style, byte canAddOrDelete, String customCategoryId, String jsonData, String description, String groupName) {
       this.id = id;
       this.moduleGroupId = moduleGroupId;
       this.name = name;
       this.style = style;
       this.canAddOrDelete = canAddOrDelete;
       this.customCategoryId = customCategoryId;
       this.jsonData = jsonData;
       this.description = description;
       this.groupName = groupName;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getModuleGroupId() {
        return this.moduleGroupId;
    }
    
    public void setModuleGroupId(String moduleGroupId) {
        this.moduleGroupId = moduleGroupId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getStyle() {
        return this.style;
    }
    
    public void setStyle(int style) {
        this.style = style;
    }
    public byte getCanAddOrDelete() {
        return this.canAddOrDelete;
    }
    
    public void setCanAddOrDelete(byte canAddOrDelete) {
        this.canAddOrDelete = canAddOrDelete;
    }
    public String getCustomCategoryId() {
        return this.customCategoryId;
    }
    
    public void setCustomCategoryId(String customCategoryId) {
        this.customCategoryId = customCategoryId;
    }
    public String getJsonData() {
        return this.jsonData;
    }
    
    public void setJsonData(String jsonData) {
        this.jsonData = jsonData;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }




}


