package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysConfigCategory generated by hbm2java
 */
public class SysConfigCategory  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private int dataSort;

    public SysConfigCategory() {
    }

	
    public SysConfigCategory(String id, int dataSort) {
        this.id = id;
        this.dataSort = dataSort;
    }
    public SysConfigCategory(String id, String name, String description, int dataSort) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.dataSort = dataSort;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getDataSort() {
        return this.dataSort;
    }
    
    public void setDataSort(int dataSort) {
        this.dataSort = dataSort;
    }




}


