package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysLocalResource generated by hbm2java
 */
public class SysLocalResource  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private String content;
     private String code;
     private String attachmentSavePath;
     private String rootId;
     private String parentId;
     private Integer visitLevel;
     private String visitPath;

    public SysLocalResource() {
    }

	
    public SysLocalResource(String id) {
        this.id = id;
    }
    public SysLocalResource(String id, String name, String description, String content, String code, String attachmentSavePath, String rootId, String parentId, Integer visitLevel, String visitPath) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.content = content;
       this.code = code;
       this.attachmentSavePath = attachmentSavePath;
       this.rootId = rootId;
       this.parentId = parentId;
       this.visitLevel = visitLevel;
       this.visitPath = visitPath;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getAttachmentSavePath() {
        return this.attachmentSavePath;
    }
    
    public void setAttachmentSavePath(String attachmentSavePath) {
        this.attachmentSavePath = attachmentSavePath;
    }
    public String getRootId() {
        return this.rootId;
    }
    
    public void setRootId(String rootId) {
        this.rootId = rootId;
    }
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    public Integer getVisitLevel() {
        return this.visitLevel;
    }
    
    public void setVisitLevel(Integer visitLevel) {
        this.visitLevel = visitLevel;
    }
    public String getVisitPath() {
        return this.visitPath;
    }
    
    public void setVisitPath(String visitPath) {
        this.visitPath = visitPath;
    }




}


