package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysLog generated by hbm2java
 */
public class SysLog  implements java.io.Serializable {


     private String id;
     private Integer logType;
     private String name;
     private String shortMessage;
     private String fullMessage;
     private String referrerUrl;
     private String requestUrl;
     private String mac;
     private String ip;
     private Date createTime;
     private String createUserId;

    public SysLog() {
    }

	
    public SysLog(String id) {
        this.id = id;
    }
    public SysLog(String id, Integer logType, String name, String shortMessage, String fullMessage, String referrerUrl, String requestUrl, String mac, String ip, Date createTime, String createUserId) {
       this.id = id;
       this.logType = logType;
       this.name = name;
       this.shortMessage = shortMessage;
       this.fullMessage = fullMessage;
       this.referrerUrl = referrerUrl;
       this.requestUrl = requestUrl;
       this.mac = mac;
       this.ip = ip;
       this.createTime = createTime;
       this.createUserId = createUserId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getLogType() {
        return this.logType;
    }
    
    public void setLogType(Integer logType) {
        this.logType = logType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShortMessage() {
        return this.shortMessage;
    }
    
    public void setShortMessage(String shortMessage) {
        this.shortMessage = shortMessage;
    }
    public String getFullMessage() {
        return this.fullMessage;
    }
    
    public void setFullMessage(String fullMessage) {
        this.fullMessage = fullMessage;
    }
    public String getReferrerUrl() {
        return this.referrerUrl;
    }
    
    public void setReferrerUrl(String referrerUrl) {
        this.referrerUrl = referrerUrl;
    }
    public String getRequestUrl() {
        return this.requestUrl;
    }
    
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }




}


