package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysModuleGroup generated by hbm2java
 */
public class SysModuleGroup  implements java.io.Serializable {


     private String id;
     private String description;
     private String displayName;
     private String englishName;
     private String imgUrl;
     private Integer visitLevel;
     private String visitPath;
     private String rootId;
     private String parentId;
     private Integer dataSort;
     private Integer dataStatus;
     private Byte delFlag;
     private Date createTime;
     private String createUserId;
     private Date lastUpdateTime;
     private String lastUpdateUserId;

    public SysModuleGroup() {
    }

	
    public SysModuleGroup(String id) {
        this.id = id;
    }
    public SysModuleGroup(String id, String description, String displayName, String englishName, String imgUrl, Integer visitLevel, String visitPath, String rootId, String parentId, Integer dataSort, Integer dataStatus, Byte delFlag, Date createTime, String createUserId, Date lastUpdateTime, String lastUpdateUserId) {
       this.id = id;
       this.description = description;
       this.displayName = displayName;
       this.englishName = englishName;
       this.imgUrl = imgUrl;
       this.visitLevel = visitLevel;
       this.visitPath = visitPath;
       this.rootId = rootId;
       this.parentId = parentId;
       this.dataSort = dataSort;
       this.dataStatus = dataStatus;
       this.delFlag = delFlag;
       this.createTime = createTime;
       this.createUserId = createUserId;
       this.lastUpdateTime = lastUpdateTime;
       this.lastUpdateUserId = lastUpdateUserId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getEnglishName() {
        return this.englishName;
    }
    
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public Integer getVisitLevel() {
        return this.visitLevel;
    }
    
    public void setVisitLevel(Integer visitLevel) {
        this.visitLevel = visitLevel;
    }
    public String getVisitPath() {
        return this.visitPath;
    }
    
    public void setVisitPath(String visitPath) {
        this.visitPath = visitPath;
    }
    public String getRootId() {
        return this.rootId;
    }
    
    public void setRootId(String rootId) {
        this.rootId = rootId;
    }
    public String getParentId() {
        return this.parentId;
    }
    
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
    public Integer getDataSort() {
        return this.dataSort;
    }
    
    public void setDataSort(Integer dataSort) {
        this.dataSort = dataSort;
    }
    public Integer getDataStatus() {
        return this.dataStatus;
    }
    
    public void setDataStatus(Integer dataStatus) {
        this.dataStatus = dataStatus;
    }
    public Byte getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public String getLastUpdateUserId() {
        return this.lastUpdateUserId;
    }
    
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }




}


