package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysModuleRights generated by hbm2java
 */
public class SysModuleRights  implements java.io.Serializable {


     private String id;
     private String moduleId;
     private String description;
     private String rightName;
     private Integer rightValue;
     private Integer rightType;
     private Integer dataStatus;
     private Date createTime;
     private String createUserId;
     private Date lastUpdateTime;
     private String lastUpdateUserId;
     private String groupId;

    public SysModuleRights() {
    }

	
    public SysModuleRights(String id) {
        this.id = id;
    }
    public SysModuleRights(String id, String moduleId, String description, String rightName, Integer rightValue, Integer rightType, Integer dataStatus, Date createTime, String createUserId, Date lastUpdateTime, String lastUpdateUserId, String groupId) {
       this.id = id;
       this.moduleId = moduleId;
       this.description = description;
       this.rightName = rightName;
       this.rightValue = rightValue;
       this.rightType = rightType;
       this.dataStatus = dataStatus;
       this.createTime = createTime;
       this.createUserId = createUserId;
       this.lastUpdateTime = lastUpdateTime;
       this.lastUpdateUserId = lastUpdateUserId;
       this.groupId = groupId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRightName() {
        return this.rightName;
    }
    
    public void setRightName(String rightName) {
        this.rightName = rightName;
    }
    public Integer getRightValue() {
        return this.rightValue;
    }
    
    public void setRightValue(Integer rightValue) {
        this.rightValue = rightValue;
    }
    public Integer getRightType() {
        return this.rightType;
    }
    
    public void setRightType(Integer rightType) {
        this.rightType = rightType;
    }
    public Integer getDataStatus() {
        return this.dataStatus;
    }
    
    public void setDataStatus(Integer dataStatus) {
        this.dataStatus = dataStatus;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getCreateUserId() {
        return this.createUserId;
    }
    
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public String getLastUpdateUserId() {
        return this.lastUpdateUserId;
    }
    
    public void setLastUpdateUserId(String lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }




}


