package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysRoles generated by hbm2java
 */
public class SysRoles  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private Byte isSystemRole;
     private String systemName;
     private Byte active;
     private String areaCode;
     private String extCode;

    public SysRoles() {
    }

	
    public SysRoles(String id) {
        this.id = id;
    }
    public SysRoles(String id, String name, String description, Byte isSystemRole, String systemName, Byte active, String areaCode, String extCode) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.isSystemRole = isSystemRole;
       this.systemName = systemName;
       this.active = active;
       this.areaCode = areaCode;
       this.extCode = extCode;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Byte getIsSystemRole() {
        return this.isSystemRole;
    }
    
    public void setIsSystemRole(Byte isSystemRole) {
        this.isSystemRole = isSystemRole;
    }
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    public Byte getActive() {
        return this.active;
    }
    
    public void setActive(Byte active) {
        this.active = active;
    }
    public String getAreaCode() {
        return this.areaCode;
    }
    
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
    public String getExtCode() {
        return this.extCode;
    }
    
    public void setExtCode(String extCode) {
        this.extCode = extCode;
    }




}


