package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysRights generated by hbm2java
 */
public class SysRights  implements java.io.Serializable {


     private String id;
     private String moduleRightsId;
     private String roleId;
     private String hrId;
     private Integer hrType;
     private Date fromDate;
     private Date endDate;
     private String moduleId;
     private String groupId;

    public SysRights() {
    }

	
    public SysRights(String id, String moduleRightsId, String roleId) {
        this.id = id;
        this.moduleRightsId = moduleRightsId;
        this.roleId = roleId;
    }
    public SysRights(String id, String moduleRightsId, String roleId, String hrId, Integer hrType, Date fromDate, Date endDate, String moduleId, String groupId) {
       this.id = id;
       this.moduleRightsId = moduleRightsId;
       this.roleId = roleId;
       this.hrId = hrId;
       this.hrType = hrType;
       this.fromDate = fromDate;
       this.endDate = endDate;
       this.moduleId = moduleId;
       this.groupId = groupId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getModuleRightsId() {
        return this.moduleRightsId;
    }
    
    public void setModuleRightsId(String moduleRightsId) {
        this.moduleRightsId = moduleRightsId;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getHrId() {
        return this.hrId;
    }
    
    public void setHrId(String hrId) {
        this.hrId = hrId;
    }
    public Integer getHrType() {
        return this.hrType;
    }
    
    public void setHrType(Integer hrType) {
        this.hrType = hrType;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId;
    }
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }




}


