package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * SysUserRoleRelationShips generated by hbm2java
 */
public class SysUserRoleRelationShips  implements java.io.Serializable {


     private String id;
     private String userId;
     private String roleId;

    public SysUserRoleRelationShips() {
    }

    public SysUserRoleRelationShips(String id, String userId, String roleId) {
       this.id = id;
       this.userId = userId;
       this.roleId = roleId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }




}


