package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SysUsers generated by hbm2java
 */
public class SysUsers  implements java.io.Serializable {


     private String id;
     private String username;
     private String password;
     private String realname;
     private Integer sex;
     private String tel;
     private String moblie;
     private String idNo;
     private Integer loginTimes;
     private Date lastLoginTime;
     private Integer delFlag;
     private Integer dataStatus;
     private Date createTime;
     private String lastIpAddress;
     private Date lastActivityDate;
     private Date lastUpdateTime;

    public SysUsers() {
    }

	
    public SysUsers(String id) {
        this.id = id;
    }
    public SysUsers(String id, String username, String password, String realname, Integer sex, String tel, String moblie, String idNo, Integer loginTimes, Date lastLoginTime, Integer delFlag, Integer dataStatus, Date createTime, String lastIpAddress, Date lastActivityDate, Date lastUpdateTime) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.realname = realname;
       this.sex = sex;
       this.tel = tel;
       this.moblie = moblie;
       this.idNo = idNo;
       this.loginTimes = loginTimes;
       this.lastLoginTime = lastLoginTime;
       this.delFlag = delFlag;
       this.dataStatus = dataStatus;
       this.createTime = createTime;
       this.lastIpAddress = lastIpAddress;
       this.lastActivityDate = lastActivityDate;
       this.lastUpdateTime = lastUpdateTime;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRealname() {
        return this.realname;
    }
    
    public void setRealname(String realname) {
        this.realname = realname;
    }
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getMoblie() {
        return this.moblie;
    }
    
    public void setMoblie(String moblie) {
        this.moblie = moblie;
    }
    public String getIdNo() {
        return this.idNo;
    }
    
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }
    public Integer getLoginTimes() {
        return this.loginTimes;
    }
    
    public void setLoginTimes(Integer loginTimes) {
        this.loginTimes = loginTimes;
    }
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
    public Integer getDataStatus() {
        return this.dataStatus;
    }
    
    public void setDataStatus(Integer dataStatus) {
        this.dataStatus = dataStatus;
    }
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public String getLastIpAddress() {
        return this.lastIpAddress;
    }
    
    public void setLastIpAddress(String lastIpAddress) {
        this.lastIpAddress = lastIpAddress;
    }
    public Date getLastActivityDate() {
        return this.lastActivityDate;
    }
    
    public void setLastActivityDate(Date lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }




}


