package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwAllowGate generated by hbm2java
 */
public class THwAllowGate  implements java.io.Serializable {


     private String allowGateId;
     private String userId;
     private String gateId;
     private int isPermanent;
     private Date startTime;
     private Date endTime;
     private Integer isdel;

    public THwAllowGate() {
    }

	
    public THwAllowGate(String allowGateId, String userId, String gateId, int isPermanent, Date startTime, Date endTime) {
        this.allowGateId = allowGateId;
        this.userId = userId;
        this.gateId = gateId;
        this.isPermanent = isPermanent;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public THwAllowGate(String allowGateId, String userId, String gateId, int isPermanent, Date startTime, Date endTime, Integer isdel) {
       this.allowGateId = allowGateId;
       this.userId = userId;
       this.gateId = gateId;
       this.isPermanent = isPermanent;
       this.startTime = startTime;
       this.endTime = endTime;
       this.isdel = isdel;
    }
   
    public String getAllowGateId() {
        return this.allowGateId;
    }
    
    public void setAllowGateId(String allowGateId) {
        this.allowGateId = allowGateId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getGateId() {
        return this.gateId;
    }
    
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }
    public int getIsPermanent() {
        return this.isPermanent;
    }
    
    public void setIsPermanent(int isPermanent) {
        this.isPermanent = isPermanent;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Integer getIsdel() {
        return this.isdel;
    }
    
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }




}


