package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwCondition generated by hbm2java
 */
public class THwCondition  implements java.io.Serializable {


     private String id;
     private Integer proCode;
     private String speciality;
     private Integer extractPersons;
     private Integer joinPersons;
     private Integer actualPersons;
     private Date createDate;

    public THwCondition() {
    }

	
    public THwCondition(String id) {
        this.id = id;
    }
    public THwCondition(String id, Integer proCode, String speciality, Integer extractPersons, Integer joinPersons, Integer actualPersons, Date createDate) {
       this.id = id;
       this.proCode = proCode;
       this.speciality = speciality;
       this.extractPersons = extractPersons;
       this.joinPersons = joinPersons;
       this.actualPersons = actualPersons;
       this.createDate = createDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getProCode() {
        return this.proCode;
    }
    
    public void setProCode(Integer proCode) {
        this.proCode = proCode;
    }
    public String getSpeciality() {
        return this.speciality;
    }
    
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }
    public Integer getExtractPersons() {
        return this.extractPersons;
    }
    
    public void setExtractPersons(Integer extractPersons) {
        this.extractPersons = extractPersons;
    }
    public Integer getJoinPersons() {
        return this.joinPersons;
    }
    
    public void setJoinPersons(Integer joinPersons) {
        this.joinPersons = joinPersons;
    }
    public Integer getActualPersons() {
        return this.actualPersons;
    }
    
    public void setActualPersons(Integer actualPersons) {
        this.actualPersons = actualPersons;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


