package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwEnterHistory generated by hbm2java
 */
public class THwEnterHistory  implements java.io.Serializable {


     private String id;
     private String expertName;
     private String sex;
     private String cardId;
     private String phone;
     private String proName;
     private String room;
     private Date arriveTime;
     private String checkinState;
     private String gateName;
     private String controlerName;
     private Date createDate;

    public THwEnterHistory() {
    }

	
    public THwEnterHistory(String id) {
        this.id = id;
    }
    public THwEnterHistory(String id, String expertName, String sex, String cardId, String phone, String proName, String room, Date arriveTime, String checkinState, String gateName, String controlerName, Date createDate) {
       this.id = id;
       this.expertName = expertName;
       this.sex = sex;
       this.cardId = cardId;
       this.phone = phone;
       this.proName = proName;
       this.room = room;
       this.arriveTime = arriveTime;
       this.checkinState = checkinState;
       this.gateName = gateName;
       this.controlerName = controlerName;
       this.createDate = createDate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getExpertName() {
        return this.expertName;
    }
    
    public void setExpertName(String expertName) {
        this.expertName = expertName;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getCardId() {
        return this.cardId;
    }
    
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getRoom() {
        return this.room;
    }
    
    public void setRoom(String room) {
        this.room = room;
    }
    public Date getArriveTime() {
        return this.arriveTime;
    }
    
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }
    public String getCheckinState() {
        return this.checkinState;
    }
    
    public void setCheckinState(String checkinState) {
        this.checkinState = checkinState;
    }
    public String getGateName() {
        return this.gateName;
    }
    
    public void setGateName(String gateName) {
        this.gateName = gateName;
    }
    public String getControlerName() {
        return this.controlerName;
    }
    
    public void setControlerName(String controlerName) {
        this.controlerName = controlerName;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


