package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwFingerprint generated by hbm2java
 */
public class THwFingerprint  implements java.io.Serializable {


     private String fingerprintId;
     private String userId;
     private Date createtime;
     private String creator;
     private String features;
     private Integer sort;
     private String fingerprint;

    public THwFingerprint() {
    }

	
    public THwFingerprint(String fingerprintId, String userId, Date createtime, String creator) {
        this.fingerprintId = fingerprintId;
        this.userId = userId;
        this.createtime = createtime;
        this.creator = creator;
    }
    public THwFingerprint(String fingerprintId, String userId, Date createtime, String creator, String features, Integer sort, String fingerprint) {
       this.fingerprintId = fingerprintId;
       this.userId = userId;
       this.createtime = createtime;
       this.creator = creator;
       this.features = features;
       this.sort = sort;
       this.fingerprint = fingerprint;
    }
   
    public String getFingerprintId() {
        return this.fingerprintId;
    }
    
    public void setFingerprintId(String fingerprintId) {
        this.fingerprintId = fingerprintId;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public String getFeatures() {
        return this.features;
    }
    
    public void setFeatures(String features) {
        this.features = features;
    }
    public Integer getSort() {
        return this.sort;
    }
    
    public void setSort(Integer sort) {
        this.sort = sort;
    }
    public String getFingerprint() {
        return this.fingerprint;
    }
    
    public void setFingerprint(String fingerprint) {
        this.fingerprint = fingerprint;
    }




}


