package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1



/**
 * THwGateRoom generated by hbm2java
 */
public class THwGateRoom  implements java.io.Serializable {


     private String gateRoomId;
     private String gateId;
     private String roomId;
     private int isdel;
     private String roomName;
     private String roomCode;

    public THwGateRoom() {
    }

	
    public THwGateRoom(String gateRoomId, String gateId, String roomId, int isdel) {
        this.gateRoomId = gateRoomId;
        this.gateId = gateId;
        this.roomId = roomId;
        this.isdel = isdel;
    }
    public THwGateRoom(String gateRoomId, String gateId, String roomId, int isdel, String roomName, String roomCode) {
       this.gateRoomId = gateRoomId;
       this.gateId = gateId;
       this.roomId = roomId;
       this.isdel = isdel;
       this.roomName = roomName;
       this.roomCode = roomCode;
    }
   
    public String getGateRoomId() {
        return this.gateRoomId;
    }
    
    public void setGateRoomId(String gateRoomId) {
        this.gateRoomId = gateRoomId;
    }
    public String getGateId() {
        return this.gateId;
    }
    
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }
    public String getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }
    public int getIsdel() {
        return this.isdel;
    }
    
    public void setIsdel(int isdel) {
        this.isdel = isdel;
    }
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
    public String getRoomCode() {
        return this.roomCode;
    }
    
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }




}


