package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwGateControl generated by hbm2java
 */
public class THwGateControl  implements java.io.Serializable {


     private String controlId;
     private String gateId;
     private String controlKey;
     private String controlNo;
     private String controlLoc;
     private String controlType;
     private Date createtime;
     private String creator;

    public THwGateControl() {
    }

    public THwGateControl(String controlId, String gateId, String controlKey, String controlNo, String controlLoc, String controlType, Date createtime, String creator) {
       this.controlId = controlId;
       this.gateId = gateId;
       this.controlKey = controlKey;
       this.controlNo = controlNo;
       this.controlLoc = controlLoc;
       this.controlType = controlType;
       this.createtime = createtime;
       this.creator = creator;
    }
   
    public String getControlId() {
        return this.controlId;
    }
    
    public void setControlId(String controlId) {
        this.controlId = controlId;
    }
    public String getGateId() {
        return this.gateId;
    }
    
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }
    public String getControlKey() {
        return this.controlKey;
    }
    
    public void setControlKey(String controlKey) {
        this.controlKey = controlKey;
    }
    public String getControlNo() {
        return this.controlNo;
    }
    
    public void setControlNo(String controlNo) {
        this.controlNo = controlNo;
    }
    public String getControlLoc() {
        return this.controlLoc;
    }
    
    public void setControlLoc(String controlLoc) {
        this.controlLoc = controlLoc;
    }
    public String getControlType() {
        return this.controlType;
    }
    
    public void setControlType(String controlType) {
        this.controlType = controlType;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }




}


