package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwGate generated by hbm2java
 */
public class THwGate  implements java.io.Serializable {


     private String gateId;
     private String gateKey;
     private String gateAddress;
     private String gateType;
     private String gateLoc;
     private Date createtime;
     private String creator;
     private int isdel;
     private String gateSn;
     private int gatePort;
     private int gateNum;

    public THwGate() {
    }

    public THwGate(String gateId, String gateKey, String gateAddress, String gateType, String gateLoc, Date createtime, String creator, int isdel, String gateSn, int gatePort, int gateNum) {
       this.gateId = gateId;
       this.gateKey = gateKey;
       this.gateAddress = gateAddress;
       this.gateType = gateType;
       this.gateLoc = gateLoc;
       this.createtime = createtime;
       this.creator = creator;
       this.isdel = isdel;
       this.gateSn = gateSn;
       this.gatePort = gatePort;
       this.gateNum = gateNum;
    }
   
    public String getGateId() {
        return this.gateId;
    }
    
    public void setGateId(String gateId) {
        this.gateId = gateId;
    }
    public String getGateKey() {
        return this.gateKey;
    }
    
    public void setGateKey(String gateKey) {
        this.gateKey = gateKey;
    }
    public String getGateAddress() {
        return this.gateAddress;
    }
    
    public void setGateAddress(String gateAddress) {
        this.gateAddress = gateAddress;
    }
    public String getGateType() {
        return this.gateType;
    }
    
    public void setGateType(String gateType) {
        this.gateType = gateType;
    }
    public String getGateLoc() {
        return this.gateLoc;
    }
    
    public void setGateLoc(String gateLoc) {
        this.gateLoc = gateLoc;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }
    public int getIsdel() {
        return this.isdel;
    }
    
    public void setIsdel(int isdel) {
        this.isdel = isdel;
    }
    public String getGateSn() {
        return this.gateSn;
    }
    
    public void setGateSn(String gateSn) {
        this.gateSn = gateSn;
    }
    public int getGatePort() {
        return this.gatePort;
    }
    
    public void setGatePort(int gatePort) {
        this.gatePort = gatePort;
    }
    public int getGateNum() {
        return this.gateNum;
    }
    
    public void setGateNum(int gateNum) {
        this.gateNum = gateNum;
    }




}


