package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * THwProjectInfo generated by hbm2java
 */
public class THwProjectInfo  implements java.io.Serializable {


     private String id;
     private Integer proCode;
     private String proName;
     private String roomName;
     private Date startTime;
     private Date endTime;
     private Integer projectState;
     private String company;
     private Date createDate;
     private String roomCode;
     private String proCode2;

    public THwProjectInfo() {
    }

	
    public THwProjectInfo(String id, String proName, String roomName, Date startTime, String company, Date createDate) {
        this.id = id;
        this.proName = proName;
        this.roomName = roomName;
        this.startTime = startTime;
        this.company = company;
        this.createDate = createDate;
    }
    public THwProjectInfo(String id, Integer proCode, String proName, String roomName, Date startTime, Date endTime, Integer projectState, String company, Date createDate, String roomCode, String proCode2) {
       this.id = id;
       this.proCode = proCode;
       this.proName = proName;
       this.roomName = roomName;
       this.startTime = startTime;
       this.endTime = endTime;
       this.projectState = projectState;
       this.company = company;
       this.createDate = createDate;
       this.roomCode = roomCode;
       this.proCode2 = proCode2;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Integer getProCode() {
        return this.proCode;
    }
    
    public void setProCode(Integer proCode) {
        this.proCode = proCode;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Integer getProjectState() {
        return this.projectState;
    }
    
    public void setProjectState(Integer projectState) {
        this.projectState = projectState;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getRoomCode() {
        return this.roomCode;
    }
    
    public void setRoomCode(String roomCode) {
        this.roomCode = roomCode;
    }
    public String getProCode2() {
        return this.proCode2;
    }
    
    public void setProCode2(String proCode2) {
        this.proCode2 = proCode2;
    }




}


