package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WfPageCheckInfo generated by hbm2java
 */
public class WfPageCheckInfo  implements java.io.Serializable {


     private String id;
     private String entityId;
     private String flowId;
     private String nodeId;
     private String nodeCode;
     private String checkInfo;
     private String checkStatu;
     private Date checkTime;
     private String checkUserId;
     private String checkUserName;
     private String systemName;
     private String childProcessId;
     private String checkFileId;

    public WfPageCheckInfo() {
    }

	
    public WfPageCheckInfo(String id) {
        this.id = id;
    }
    public WfPageCheckInfo(String id, String entityId, String flowId, String nodeId, String nodeCode, String checkInfo, String checkStatu, Date checkTime, String checkUserId, String checkUserName, String systemName, String childProcessId, String checkFileId) {
       this.id = id;
       this.entityId = entityId;
       this.flowId = flowId;
       this.nodeId = nodeId;
       this.nodeCode = nodeCode;
       this.checkInfo = checkInfo;
       this.checkStatu = checkStatu;
       this.checkTime = checkTime;
       this.checkUserId = checkUserId;
       this.checkUserName = checkUserName;
       this.systemName = systemName;
       this.childProcessId = childProcessId;
       this.checkFileId = checkFileId;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }
    public String getFlowId() {
        return this.flowId;
    }
    
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }
    public String getNodeCode() {
        return this.nodeCode;
    }
    
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }
    public String getCheckInfo() {
        return this.checkInfo;
    }
    
    public void setCheckInfo(String checkInfo) {
        this.checkInfo = checkInfo;
    }
    public String getCheckStatu() {
        return this.checkStatu;
    }
    
    public void setCheckStatu(String checkStatu) {
        this.checkStatu = checkStatu;
    }
    public Date getCheckTime() {
        return this.checkTime;
    }
    
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }
    public String getCheckUserId() {
        return this.checkUserId;
    }
    
    public void setCheckUserId(String checkUserId) {
        this.checkUserId = checkUserId;
    }
    public String getCheckUserName() {
        return this.checkUserName;
    }
    
    public void setCheckUserName(String checkUserName) {
        this.checkUserName = checkUserName;
    }
    public String getSystemName() {
        return this.systemName;
    }
    
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }
    public String getChildProcessId() {
        return this.childProcessId;
    }
    
    public void setChildProcessId(String childProcessId) {
        this.childProcessId = childProcessId;
    }
    public String getCheckFileId() {
        return this.checkFileId;
    }
    
    public void setCheckFileId(String checkFileId) {
        this.checkFileId = checkFileId;
    }




}


