package datura.sys.entity;
// Generated 2014-12-17 22:28:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WfTest generated by hbm2java
 */
public class WfTest  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private Date createDate;
     private String flowStep;

    public WfTest() {
    }

	
    public WfTest(String id) {
        this.id = id;
    }
    public WfTest(String id, String name, String description, Date createDate, String flowStep) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.createDate = createDate;
       this.flowStep = flowStep;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getFlowStep() {
        return this.flowStep;
    }
    
    public void setFlowStep(String flowStep) {
        this.flowStep = flowStep;
    }




}


